/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package apresentacao;

/**
 *
 * @author Ramon
 */
public class fmAnamnese extends javax.swing.JInternalFrame {

    /**
     * Creates new form fmAnamnese
     */
    public fmAnamnese() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbPacientes = new javax.swing.JComboBox<>();
        cbPsicologos = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQueixas = new javax.swing.JTextField();
        txtSintomas = new javax.swing.JTextField();
        txtTratamentosAnteriores = new javax.swing.JTextField();
        txtMedicamentos = new javax.swing.JTextField();
        txtInfancia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRotina = new javax.swing.JTextField();
        txtVicios = new javax.swing.JTextField();
        txtHobbies = new javax.swing.JTextField();
        txtTrabalho = new javax.swing.JTextField();
        txtHistoricoFamiliar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtComportamento = new javax.swing.JTextField();
        txtLinguagem = new javax.swing.JTextField();
        txtHumor = new javax.swing.JTextField();
        txtHipoteseDiagnostica = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtValorSessao = new javax.swing.JTextField();
        cbPeriodicidade = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        txtNumeroSessoes = new javax.swing.JSpinner();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro Anamnese");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Anamnese");

        jLabel2.setText("Paciente:");

        jLabel3.setText("Psicologo:");

        cbPacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbPsicologos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Queixas:");

        jLabel5.setText("Sintomas:");

        jLabel6.setText("<html>Tratamento<br>anteriores:</html>");

        jLabel7.setText("Medicamentos:");

        jLabel8.setText("Infância:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(7, 7, 7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQueixas)
                    .addComponent(txtSintomas)
                    .addComponent(txtTratamentosAnteriores)
                    .addComponent(txtMedicamentos)
                    .addComponent(txtInfancia, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQueixas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txtTratamentosAnteriores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInfancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Antecedentes", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel9.setText("Rotina:");

        jLabel10.setText("Vicios:");

        jLabel11.setText("Hobbies:");

        jLabel12.setText("Trabalho:");

        jLabel13.setText("<html>Histórico<br>Familiar:</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10))
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRotina)
                    .addComponent(txtVicios)
                    .addComponent(txtHobbies)
                    .addComponent(txtTrabalho)
                    .addComponent(txtHistoricoFamiliar, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRotina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtVicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtHobbies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHistoricoFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rotina", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel14.setText("Comportamento:");

        jLabel15.setText("Linguagem:");

        jLabel16.setText("Humor:");

        jLabel17.setText("Hipotese diágnostica:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtComportamento)
                    .addComponent(txtLinguagem)
                    .addComponent(txtHumor)
                    .addComponent(txtHipoteseDiagnostica, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtComportamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtLinguagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtHumor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtHipoteseDiagnostica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comportamento", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel18.setText("Número de sessões:");

        jLabel19.setText("Valor sessão:");

        jLabel20.setText("Periodicidade:");

        jLabel21.setText("Observações:");

        cbPeriodicidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanal", "Quinzenal", "Mensal", " " }));

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        txtNumeroSessoes.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtValorSessao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPeriodicidade, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                            .addComponent(txtNumeroSessoes))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtNumeroSessoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtValorSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbPeriodicidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Outros", jPanel4);

        btNovo.setText("Novo");
        btNovo.addActionListener(this::btNovoActionPerformed);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(this::btSalvarActionPerformed);

        btSair.setText("Sair");
        btSair.addActionListener(this::btSairActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbPacientes, 0, 104, Short.MAX_VALUE)
                                    .addComponent(cbPsicologos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTabbedPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSair)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPsicologos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btSalvar)
                    .addComponent(btSair))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            // --- 1. Carregar Pacientes no ComboBox ---
            persistencia.IPacienteDAO dao = new persistencia.PacienteDAO();
            java.util.List<negocio.Paciente> lista = dao.listarTodos();
            
            javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
            
            for (negocio.Paciente paciente : lista) {
                // Adiciona "ID - Nome" na lista visual
                modelo.addElement(paciente.getIdPaciente() + " - " + paciente.getNome());
            }
            cbPacientes.setModel(modelo);

            
            // --- 2. Carregar Psicólogos no ComboBox ---
            // Nota: Verifique se você já criou a interface IPsicologoDAO. 
            // Se não, use apenas 'PsicologoDAO dao2 = new PsicologoDAO();'
            persistencia.IPsicologoDAO dao2 = new persistencia.PsicologoDAO();
            java.util.List<negocio.Psicologo> lista2 = dao2.listarTodos();
            
            javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
            
            for (negocio.Psicologo psicologo : lista2) {
                // Adiciona "ID - Nome" na lista visual
                modelo2.addElement(psicologo.getIdPsicologo() + " - " + psicologo.getNome());
            }
            cbPsicologos.setModel(modelo2);
            
        } catch (Exception e) {
            System.out.println(e.toString());
            javax.swing.JOptionPane.showMessageDialog(null, "Houve um erro ao carregar os dados: " + e.getMessage());
        }
        
        habilitar(false); //Desabilitar os componentes
        limpar(); //Limpar os componente
        
    }//GEN-LAST:event_formInternalFrameOpened
    

    public void habilitar(boolean valor) {
        // 1. Comboboxes (Seleção de Paciente, Psicólogo e Periodicidade)
        cbPacientes.setEnabled(valor);
        cbPsicologos.setEnabled(valor);
        cbPeriodicidade.setEnabled(valor);
        
        txtQueixas.setEnabled(valor);
        txtSintomas.setEnabled(valor);
        txtTratamentosAnteriores.setEnabled(valor);
        txtMedicamentos.setEnabled(valor);
        txtInfancia.setEnabled(valor);
        
        // 2. Campos de Texto (Strings)
        txtRotina.setEnabled(valor);
        txtVicios.setEnabled(valor);
        txtHobbies.setEnabled(valor);
        txtTrabalho.setEnabled(valor);
        txtHistoricoFamiliar.setEnabled(valor);
        txtComportamento.setEnabled(valor);
        txtLinguagem.setEnabled(valor);
        txtHumor.setEnabled(valor);
        txtHipoteseDiagnostica.setEnabled(valor);
        txtObservacoes.setEnabled(valor);

        // 3. Campos Numéricos
        txtNumeroSessoes.setEnabled(valor);
        txtValorSessao.setEnabled(valor);

        // 4. Botões de Ação
        btSalvar.setEnabled(valor);
        
        // O botão Novo inverte a lógica (se estou editando, não posso criar novo)
        // Certifique-se de ter um botão chamado btNovo na sua tela
        if (btNovo != null) { 
            btNovo.setEnabled(!valor);
        }
    }

    public void limpar() {
        // 1. Limpar Seleções dos Comboboxes
        cbPacientes.setSelectedIndex(-1);
        cbPsicologos.setSelectedIndex(-1);
        cbPeriodicidade.setSelectedIndex(-1);
        
        txtQueixas.setText("");
        txtSintomas.setText("");
        txtTratamentosAnteriores.setText("");
        txtMedicamentos.setText("");
        txtInfancia.setText("");
        
        // 2. Limpar Campos de Texto
        txtRotina.setText("");
        txtVicios.setText("");
        txtHobbies.setText("");
        txtTrabalho.setText("");
        txtHistoricoFamiliar.setText("");
        txtComportamento.setText("");
        txtLinguagem.setText("");
        txtHumor.setText("");
        txtHipoteseDiagnostica.setText("");
        txtObservacoes.setText("");
        txtValorSessao.setText("");

        // 3. Limpar Campo de Número de Sessões
        // SE FOR UM JTextField (Caixa de texto comum):
        txtNumeroSessoes.setValue(0);
        
        // SE FOR UM JSpinner (Aquele com setinhas), USE ESTA LINHA ABAIXO NO LUGAR:
        // txtNumeroSessoes.setValue(0);
    }
    
    
    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
                                                
        int valor = javax.swing.JOptionPane.showConfirmDialog(null, "Tem certeza que deseja salvar a Anamnese?", "Sistema Consultório", 1);
        
        if (valor == 0) {
            negocio.Anamnese anamnese = new negocio.Anamnese();
            
            try {
                // 1. RECUPERANDO OS IDs DOS COMBOBOXES
                if (cbPacientes.getSelectedIndex() != -1) {
                    String itemPac = cbPacientes.getSelectedItem().toString();
                    String[] partesPac = itemPac.split(" - ");
                    anamnese.setIdPaciente(Integer.parseInt(partesPac[0])); 
                }
                
                if (cbPsicologos.getSelectedIndex() != -1) {
                    String itemPsi = cbPsicologos.getSelectedItem().toString();
                    String[] partesPsi = itemPsi.split(" - ");
                    anamnese.setIdPsicologo(Integer.parseInt(partesPsi[0]));
                }
                
                // 2. CAMPOS DE TEXTO (INCLUINDO OS QUE FALTAVAM)
                anamnese.setQueixas(txtQueixas.getText());
                anamnese.setSintomas(txtSintomas.getText());
                
                // Atenção aos nomes dos métodos da sua classe (com underline)
                anamnese.setTratamentos_anteriores(txtTratamentosAnteriores.getText());
                
                anamnese.setMedicamentos(txtMedicamentos.getText());
                anamnese.setInfancia(txtInfancia.getText());

                // 2. CAMPOS DE TEXTO
                // Ajustei todos os nomes abaixo para ficarem iguais à sua classe Anamnese
                anamnese.setRotina(txtRotina.getText());
                anamnese.setVicios(txtVicios.getText());
                anamnese.setHobbies(txtHobbies.getText());
                anamnese.setTrabalho(txtTrabalho.getText());
                
                // Atenção aos underlines (_) que você usou na classe:
                anamnese.setHistorico_familiar(txtHistoricoFamiliar.getText());
                
                anamnese.setComportamento(txtComportamento.getText());
                anamnese.setLinguagem(txtLinguagem.getText());
                anamnese.setHumor(txtHumor.getText());
                
                anamnese.setHipotese_diagnostico(txtHipoteseDiagnostica.getText());
                anamnese.setPeriodicidade(cbPeriodicidade.getSelectedItem().toString());
                anamnese.setObservacoes(txtObservacoes.getText());

                // 3. CAMPOS NUMÉRICOS
                
                // NÚMERO DE SESSÕES
                // Se for JSpinner:
                // anamnese.setNumero_sessoes((Integer) txtNumeroSessoes.getValue());
                
                // Se for JTextField (Caixa de Texto comum):
                int qtdSessoes = (Integer) txtNumeroSessoes.getValue();
                anamnese.setNumero_sessoes(qtdSessoes);
                
                // VALOR DA SESSÃO (FLOAT)
                // Sua classe pede Float, então usamos Float.parseFloat
                String valorStr = txtValorSessao.getText().replace(",", ".");
                if (!valorStr.isEmpty()) {
                    anamnese.setValor_sessao(Float.parseFloat(valorStr));
                }

                // 4. GRAVANDO NO BANCO
                persistencia.IAnamneseDAO dao = new persistencia.AnamneseDAO();
                dao.adicionar(anamnese);
                
                javax.swing.JOptionPane.showMessageDialog(null, "Anamnese salva com sucesso!");
                
                limpar(); // Certifique-se de ter criado este método limpar() na tela de Anamnese
                // habilitar(false); // Se tiver esse método

            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Erro nos números: Verifique Valor ou Nº Sessões.\n" + e.getMessage());
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Erro ao salvar: " + e.getMessage());
            }
        }
        
        habilitar(false); //Desabilitar os componentes
        limpar(); //Limpar os componente
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        
        habilitar(true); //Habilitar componentes
        limpar(); //Preparamos os componentes para insergéo de dados
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbPacientes;
    private javax.swing.JComboBox<String> cbPeriodicidade;
    private javax.swing.JComboBox<String> cbPsicologos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtComportamento;
    private javax.swing.JTextField txtHipoteseDiagnostica;
    private javax.swing.JTextField txtHistoricoFamiliar;
    private javax.swing.JTextField txtHobbies;
    private javax.swing.JTextField txtHumor;
    private javax.swing.JTextField txtInfancia;
    private javax.swing.JTextField txtLinguagem;
    private javax.swing.JTextField txtMedicamentos;
    private javax.swing.JSpinner txtNumeroSessoes;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtQueixas;
    private javax.swing.JTextField txtRotina;
    private javax.swing.JTextField txtSintomas;
    private javax.swing.JTextField txtTrabalho;
    private javax.swing.JTextField txtTratamentosAnteriores;
    private javax.swing.JTextField txtValorSessao;
    private javax.swing.JTextField txtVicios;
    // End of variables declaration//GEN-END:variables
}
