/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package apresentacao;

/**
 *
 * @author Ramon
 */
public class fmSessao extends javax.swing.JInternalFrame {

    /**
     * Creates new form fmSessao
     */
    public fmSessao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        txtQueixas = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        txtResumo = new javax.swing.JTextField();
        cbPago = new javax.swing.JComboBox<>();
        cbPlano = new javax.swing.JComboBox<>();
        txtEvo = new javax.swing.JSpinner();
        btSair = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbPacientes = new javax.swing.JComboBox<>();
        cbAnamnese = new javax.swing.JComboBox<>();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Sessão");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel2.setText("Data:");

        jLabel3.setText("Queixas");

        jLabel4.setText("Plano:");

        jLabel5.setText("Diagnostico:");

        jLabel6.setText("Resumo:");

        jLabel7.setText("Evolução:");

        jLabel8.setText("Pago:");

        cbPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim\t", "Não", " " }));

        cbPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amil Saúde", "Bio Saúde", "Bradesco Seguro Saúde", "Caixa Seguro Saúde", "Greenline Saúde", "Unimed Fesp" }));

        txtEvo.setModel(new javax.swing.SpinnerNumberModel(10, 10, 10, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData)
                    .addComponent(txtQueixas)
                    .addComponent(txtDiagnostico)
                    .addComponent(txtResumo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEvo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbPago, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQueixas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtResumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btSair.setText("Sair");
        btSair.addActionListener(this::btSairActionPerformed);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(this::btSalvarActionPerformed);

        jLabel9.setText("Paciente:");

        jLabel10.setText("Anamnese:");

        cbPacientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbAnamnese.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair)
                .addGap(4, 4, 4))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 93, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbPacientes, 0, 112, Short.MAX_VALUE)
                            .addComponent(cbAnamnese, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbAnamnese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:                                       
        try {
            // --- 1. Carregar Pacientes no ComboBox ---
            persistencia.IPacienteDAO dao = new persistencia.PacienteDAO();
            java.util.List<negocio.Paciente> lista = dao.listarTodos();
            
            javax.swing.DefaultComboBoxModel modelo = new javax.swing.DefaultComboBoxModel();
            
            for (negocio.Paciente paciente : lista) {
                // Adiciona "ID - Nome"
                modelo.addElement(paciente.getIdPaciente() + " - " + paciente.getNome());
            }
            cbPacientes.setModel(modelo);

            
            // --- 2. Carregar Anamneses no ComboBox ---
            // Substituímos Psicólogo por Anamnese aqui
            persistencia.IAnamneseDAO dao2 = new persistencia.AnamneseDAO();
            java.util.List<negocio.Anamnese> lista2 = dao2.listarTodos();
            
            javax.swing.DefaultComboBoxModel modelo2 = new javax.swing.DefaultComboBoxModel();
            
            for (negocio.Anamnese anamnese : lista2) {
                // Exibe: "ID Anamnese - Paciente: ID Paciente"
                // Isso ajuda a saber de quem é aquela ficha de anamnese
                modelo2.addElement(anamnese.getIdAnamnese() + " - Paciente cód: " + anamnese.getIdPaciente());
            }
            cbAnamnese.setModel(modelo2);
            
        } catch (Exception e) {
            System.out.println(e.toString());
            javax.swing.JOptionPane.showMessageDialog(null, "Houve um erro ao carregar os dados: " + e.getMessage());
        }
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
                                               
        int valor = javax.swing.JOptionPane.showConfirmDialog(null, "Tem certeza que deseja salvar a Sessão?", "Sistema Consultório", 1);
        
        if (valor == 0) {
            negocio.Sessao sessao = new negocio.Sessao();
            
            try {
                // 1. RECUPERAR ID DA ANAMNESE (Do ComboBox)
                if (cbAnamnese.getSelectedIndex() != -1) {
                    String item = cbAnamnese.getSelectedItem().toString();
                    String[] partes = item.split(" - ");
                    // Pega a primeira parte (o ID) antes do traço
                    sessao.setIdAnamnese(Integer.parseInt(partes[0])); 
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Por favor, selecione uma Anamnese vinculada.");
                    return; // Para o código se não tiver anamnese selecionada
                }

                // 2. TRATAMENTO DA DATA E HORA (LocalDateTime)
                // O formato deve bater com a máscara do seu campo txtData. 
                // Exemplo: "30/11/2025 14:30"
                String dataTexto = txtData.getText();
                
                // DateTimeFormatter é a classe moderna para formatar datas
                java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
                java.time.LocalDateTime dataHora = java.time.LocalDateTime.parse(dataTexto, formato);
                
                sessao.setData(dataHora);


                // 3. CAMPOS DE TEXTO
                sessao.setQueixas_paciente(txtQueixas.getText());
                if (cbPlano.getSelectedItem() != null) {
                    sessao.setPlano_tratamento(cbPlano.getSelectedItem().toString());
                }
                sessao.setDiagnostico_final(txtDiagnostico.getText()); // Ou txtDiagnosticoFinal
                sessao.setResumo_sessao(txtResumo.getText());


                // 4. EVOLUÇÃO (Inteiro)
                // Se for campo de texto simples:
                // 6. EVOLUÇÃO (JSPINNER - CORREÇÃO AQUI)
                // Como é um spinner, usamos getValue() e forçamos ser um Inteiro (Integer)
                sessao.setEvolucao((Integer) txtEvo.getValue());
                // Se for JSpinner, use: sessao.setEvolucao((Integer) txtEvolucao.getValue());


                // 5. PAGAMENTO (Boolean / Checkbox)
                // Se o checkbox estiver marcado, retorna true, senão false
                if (cbPago.getSelectedItem() != null) {
                    String statusPagamento = cbPago.getSelectedItem().toString();
                    if (statusPagamento.equalsIgnoreCase("Sim")) {
                        sessao.setPago(true);
                    } else {
                        sessao.setPago(false);
                    }
                } else {
                    sessao.setPago(false); // Padrão se nada for selecionado
                }


                // 6. GRAVAR NO BANCO
                // Certifique-se de criar a classe SessaoDAO e o método adicionar
                persistencia.ISessaoDAO dao = new persistencia.SessaoDAO();
                dao.adicionar(sessao);
                
                javax.swing.JOptionPane.showMessageDialog(null, "Sessão salva com sucesso!");
                

            } catch (java.time.format.DateTimeParseException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Erro na Data/Hora.\nCertifique-se de digitar dia, mês, ano e hora (ex: 01/01/2025 14:00)");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Erro ao salvar: " + e.getMessage());
                e.printStackTrace(); // Ajuda a ver o erro no console se precisar
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbAnamnese;
    private javax.swing.JComboBox<String> cbPacientes;
    private javax.swing.JComboBox<String> cbPago;
    private javax.swing.JComboBox<String> cbPlano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JSpinner txtEvo;
    private javax.swing.JTextField txtQueixas;
    private javax.swing.JTextField txtResumo;
    // End of variables declaration//GEN-END:variables
}
